// credit to https://github.com/memset0/ZJU-Project-Report-Template/blob/master/template.typ

#let font_serif = (
  "Source Han Serif SC",
  "New Computer Modern",
  "LXGW WenKai GB Screen",
  "Noto Serif CJK SC",
  "Times New Roman",
  "Georgia",
  "STSong",
  "SimSun",
  "Songti SC",
  //   "Nimbus Roman No9 L",
  "AR PL New Sung",
  "AR PL SungtiL GB",
  "NSimSun",
  "TW\-Sung",
  "WenQuanYi Bitmap Song",
  "AR PL UMing CN",
  "AR PL UMing HK",
  "AR PL UMing TW",
  "AR PL UMing TW MBE",
  "PMingLiU",
  "MingLiU",
)
#let font_sans_serif = (
  "Noto Sans",
  "Helvetica Neue",
  "Helvetica",
  "Nimbus Sans L",
  "Arial",
  "Liberation Sans",
  "PingFang SC",
  "Hiragino Sans GB",
  "Noto Sans CJK SC",
  "Source Han Sans SC",
  "Source Han Sans CN",
  "Microsoft YaHei",
  "Wenquanyi Micro Hei",
  "WenQuanYi Zen Hei",
  "ST Heiti",
  "SimHei",
  "WenQuanYi Zen Hei Sharp",
)
#let font_mono = ("Maple Mono NF", "Consolas", "Monaco", ..font_sans_serif)
